### ISSUE TITLE
Question on how to use ...

### ISSUE THREAD

**Issue by wowo4k** [exyte/ConcentricOnboarding#1]
Thanks for this very nice Onboarding Screen. 
My question is related how you envision to leave the cycle after cycling through e.g. 4 screens and then navigate to different screen. 
I also wonder if you thought about how to perform different actions between the different screens, e.g. asking for Location service permission, Phone book permission, PushNotification permission  

Thanks Armin

**Comment by f3dm76** [comment]
Hello wowo4k, 
You are the one in control of all the content pages and navigation bar buttons - you can add whatever functionality you want with them. You also have a couple of closures at your disposal, like `didGoToLastPage`.

**Comment by wowo4k** [comment]
Hello f3dm76,

Many thanks for feedback. I figured out how to change my views and have the interaction as needed. I only struggle with the closures like didGoToLastPage, I always get this closures strikethrough in Xcode. Would you mind to share a simple Codefragment how to use them based on your Example Code??

Thanks Armin

**Comment by f3dm76** [comment]
You are correct, thank you for the catch! Fixed this callback not being called, also added   `didPressNextButton`, so you can change what the button does once you reach the last page for example. Check out new pod version - 0.0.2

**Comment by d0hnj0e** [comment]
Thanks a lot for this library! 

I am facing the same problem as @wowo4k; can you tell me, where I can tell `didGoToLastPage` and how I can manage to show i.e. `FirstViewController`after showing all onboarding screens, @f3dm76? 

I tried:

```
public var didGoToLastPage = {
        
        print("4")
        present(loginController, animated:true, completion:nil)
        
    }
```
but it's not working...

**Comment by f3dm76** [comment]
Hello @d0hnj0e,
I added a couple of new callbacks with which you can completely replace the action taken after you press "next" button on the last page. 
```
var yourView = ConcentricOnboardingView(pages: pages, bgColors: MockData.colors)

yourView.insteadOfCyclingToFirstPage = {
       print("do your thing")
}
```
Default behaviour is to cycle to the first page again, but if you set this callback, it will not do that, and you can navigate somewhere or do whatever you like.
I also added insteadOfCyclingToLastPage just in case someone uses backwards navigation. So please checkout version 0.0.3. If it's not working for you, please let me know, have a great day!

**Comment by mohammedabdulbasithk** [comment]
how can i redirect to a storyboard view controller from this?

**Comment by shipinev** [comment]
Hey @mohammedabdulbasithk.
You should use [UIViewControllerRepresentable](https://developer.apple.com/documentation/swiftui/uiviewcontrollerrepresentable). Also, you can check [this tutorial](https://www.hackingwithswift.com/books/ios-swiftui/wrapping-a-uiviewcontroller-in-a-swiftui-view).
I hope this will help :)

**Comment by anestis1000** [comment]
Hello
In the callback   a.insteadOfCyclingToFirstPage = {
            print("do your thing")
        }
how can i move to a new swiftUI View. In this point I don't have any navigationView or NavigationLink.
For example if i use something like that:

 a.insteadOfCyclingToFirstPage = {
           MyView()
        }
doesn't do anything (and i think its normal). I receive as warning Result of 'MyView' initializer is unused

Thanks
