### ISSUE TITLE
Issue with Swift Package Manager: Invalid Manifest

### ISSUE THREAD

**Issue by GrosserStuhl** [exyte/ConcentricOnboarding#12]
I tried to import this library multiple times, but alway get the same error:

_invalidManifestFormat("/var/folders/hq/xht3hkxj0sj9dmb9l8_s5zm40000gn/T/TemporaryFile.CbTs13.swift:8:15: error: \'v14\' is unavailable\n        .iOS(.v14)\n              ^~~\nPackageDescription.SupportedPlatform:49:27: note: \'v14\' was introduced in PackageDescription 5.3\n        public static var v14: PackageDescription.SupportedPlatform.IOSVersion\n                          ^", diagnosticFile: Optional(<AbsolutePath:"/Users/dimaprivat/Library/Developer/Xcode/DerivedData/MindMends-dhvxmufwqyjuymghawxgovoejhaf/SourcePackages/ManifestLoading/concentriconboarding.dia">)) in https://github.com/exyte/ConcentricOnboarding_

Does it not work with iOS 14?

**Comment by f3dm76** [comment]
Hey @GrosserStuhl, thank you so much for bringing this to our attention. I'm pleased to let you know I fixed the issue, you are most welcome to check out version 1.0.1. Have a wonderful day!

**Comment by GrosserStuhl** [comment]
Thanks a lot, it works now 👍
