### ISSUE TITLE
Example code does not working

### ISSUE THREAD

**Issue by TheGatesOfParadise** [exyte/ConcentricOnboarding#15]
Hi,  I used xcode 13.3,  MacOS 12.4 with M1.   The 2nd screen does not show up correctly.  Below is what I see.  

The result comes from the example code, no change at all. 

<img width="418" alt="Screen Shot 2022-07-28 at 5 17 52 PM" src="https://user-images.githubusercontent.com/109245867/181639803-5fb96e83-aac1-42a3-b60f-9edd2a4edca7.png">

**Comment by f3dm76** [comment]
Hey @TheGatesOfParadise, could you please launch in simulator? I don't thinks i can guarantee live preview behaviour

**Comment by TheGatesOfParadise** [comment]
> Hey @TheGatesOfParadise, could you please launch in simulator? I don't thinks i can guarantee live preview behaviour

You are right, simulator works fine.   Preview does not work.   Thanks for checking!

**Comment by RMehdid** [comment]
I had the same issue, dumb us 😅
