### ISSUE TITLE
Default next button is invisible

### ISSUE THREAD

**Issue by rohandalvi** [exyte/ConcentricOnboarding#16]
```
case .onboardingPage:
            if (val != nil) {
                HomeView()
            } else {
                ConcentricOnboardingView(pageContents: onboardingPages ).duration(1.0).nextIcon("chevron.forward")
                    .insteadOfCyclingToFirstPage {
                    viewRouter.currentPage = .signInPage
                }
            }
        }
```

This is the area where I expect to see the chevron.forward default next button, but I don't see it. 

<img width="240" alt="image" src="https://user-images.githubusercontent.com/1272182/192202706-920dfd0f-4d2b-4061-a724-47b185f04387.png">

**Comment by f3dm76** [comment]
Hey @rohandalvi, sorry for the late response, could you please attach a reproducible example for me? It might be that it just doesn't fit on the screen, and I need to process it better. Anyway, I'll have to see to help you

**Comment by f3dm76** [comment]
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Please be sure to attach minimal compilable reproducible example. Have a nice day!
