### ISSUE TITLE
Not working when importing with swift package manager

### ISSUE THREAD

**Issue by CyberBison** [exyte/ConcentricOnboarding#7]
Hey there !
I tried importing this library inside my project using the swift package manager. Import worked well but there's a lot of compiler error, as you can see on this: print screen.

<img width="342" alt="Screenshot 2020-10-11 at 11 16 39" src="https://user-images.githubusercontent.com/8091411/95674878-6ff04180-0bb3-11eb-8700-91b84a86d0bc.png">

I'm on Xcode 12.0.1 and my project is targeting iOS 13.4+

As a workaround I installed the file manually and it's working.

**Comment by f3dm76** [comment]
Hey @RosayGaspard, please check out brand new 0.0.5 version, where I fixed this issue, and also added support for other platforms. Have a great day!

**Comment by CyberBison** [comment]
Thank for your quick support ! I'll test it asap :)
Have a nice day !
